services:

  postgres:
    container_name: postgres
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=fabrice
      - POSTGRES_PASSWORD=@fab1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: